language: rust
sudo: required
rust:
- nightly
- beta
- 1.0.0
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test
env:
  global:
  - secure: bYuY2VgTHzglMUSDzv4l9aSTiaPPrwoP1MGqxqwo9QpEmvLhRB1mrEwb+I2h6rak/wetSGyMoo4CMXcrzcXNJWy9+qvsy2/LD6/7NK7zXKNOVZjce2jcaUGmnvUsLNzBW3pf0lyaTfEEctg1zx6Zzh0McWaKUjKDFhCYzXgNfws=
